{{- if .Values.mongo.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "solar-system.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_USERNAME: {{ .Values.mongo.username }}
  MONGO_PASSWORD: {{ .Values.mongo.password }}
  MONGO_URI: {{ .Values.mongo.uri }}
{{- end }}